// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolServiceSystem.Data;

namespace SchoolServiceSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211223202046_AddNameToService")]
    partial class AddNameToService
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("SchoolServiceSystem.Models.Bus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<string>("Plaque")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("DriverID");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("SchoolServiceSystem.Models.School", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("SecretKey")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("SchoolServiceSystem.Models.Service", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BusID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BusID");

                    b.HasIndex("SchoolID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("SchoolServiceSystem.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<string>("SurName")
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ServiceID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolServiceSystem.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolID")
                        .HasColumnType("int");

                    b.Property<string>("SurName")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SchoolServiceSystem.Models.Bus", b =>
                {
                    b.HasOne("SchoolServiceSystem.Models.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SchoolServiceSystem.Models.Service", b =>
                {
                    b.HasOne("SchoolServiceSystem.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolServiceSystem.Models.School", "School")
                        .WithMany("Services")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolServiceSystem.Models.Student", b =>
                {
                    b.HasOne("SchoolServiceSystem.Models.Service", "Service")
                        .WithMany("Students")
                        .HasForeignKey("ServiceID");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SchoolServiceSystem.Models.User", b =>
                {
                    b.HasOne("SchoolServiceSystem.Models.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolID");

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolServiceSystem.Models.School", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SchoolServiceSystem.Models.Service", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
